name: Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Semgrep (p/ci)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          generateSarif: true

      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep.sarif