name: Semgrep

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install and run Semgrep; produce SARIF + JSON (don’t fail the job)
      - name: Run Semgrep (p/ci)
        run: |
          pipx install semgrep || pip install --user semgrep
          semgrep scan --config p/ci \
            --sarif -o semgrep.sarif \
            --json  -o semgrep.json \
            --exclude node_modules --exclude .next || true

          echo "## Semgrep Summary" >> $GITHUB_STEP_SUMMARY
          COUNT=$(jq '.results | length' semgrep.json 2>/dev/null || echo 0)
          echo "- Findings: $COUNT" >> $GITHUB_STEP_SUMMARY
          echo "- Artifacts: semgrep.sarif, semgrep.json" >> $GITHUB_STEP_SUMMARY

      - name: Upload Semgrep artifacts
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: |
            semgrep.sarif
            semgrep.json